# Generated by Django 4.2.3 on 2023-09-06 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 19, 29, 42, 741665, tzinfo=datetime.timezone.utc)),
        ),
    ]
