# Generated by Django 4.2.3 on 2023-07-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Address_id',
            field=models.IntegerField(max_length=24),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_number',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cards',
            name='cards_id',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cards',
            name='cvs',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cards',
            name='date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='e_mail',
            field=models.EmailField(max_length=50),
        ),
    ]
