# Generated by Django 4.2.3 on 2023-07-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_change_status', 'Can change status'), ('can_view_dashboard', 'Can view dashboard')]},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permission',
        ),
    ]
