# Generated by Django 4.2.5 on 2023-09-07 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0002_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 12, 8, 19, 341837, tzinfo=datetime.timezone.utc)),
        ),
    ]
