# Generated by Django 4.2.3 on 2023-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
