# Generated by Django 4.2.3 on 2023-07-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0003_alter_customuser_birth_date_alter_customuser_e_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='prod_img/no_image.png', upload_to='prod_img')),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
    ]
