# Generated by Django 4.2.3 on 2023-07-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0004_alter_customuser_options_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='permission',
        ),
    ]
