# Generated by Django 4.2.3 on 2023-07-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='surname',
        ),
    ]
