# Generated by Django 4.2.3 on 2023-07-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0005_remove_customuser_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
