# Generated by Django 4.2.3 on 2023-08-06 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0008_alter_customuser_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 11, 8, 37, 568310, tzinfo=datetime.timezone.utc)),
        ),
    ]
