# Generated by Django 4.2.3 on 2023-08-08 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0009_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 13, 54, 39, 883023, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='prod_img/no_image.png', upload_to='prod_img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APİ.product')),
            ],
        ),
    ]
