# Generated by Django 4.2.3 on 2023-08-08 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0011_remove_product_image_alter_updatecode_expire_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 21, 15, 58, 621608, tzinfo=datetime.timezone.utc)),
        ),
    ]
