# Generated by Django 4.2.3 on 2023-08-09 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0012_rename_image_product_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 7, 32, 47, 347872, tzinfo=datetime.timezone.utc)),
        ),
    ]
