# Generated by Django 4.2.3 on 2023-08-09 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0014_remove_product_images_alter_updatecode_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 8, 4, 40, 561933, tzinfo=datetime.timezone.utc)),
        ),
    ]
