# Generated by Django 4.2.3 on 2023-08-09 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0015_alter_product_images_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 8, 15, 39, 454871, tzinfo=datetime.timezone.utc)),
        ),
    ]
