# Generated by Django 4.2.3 on 2023-08-09 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0017_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 9, 1, 48, 590141, tzinfo=datetime.timezone.utc)),
        ),
    ]
