# Generated by Django 4.2.3 on 2023-08-09 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0018_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='prod_img/no_image.png', upload_to='prod_img'),
        ),
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 11, 40, 51, 429476, tzinfo=datetime.timezone.utc)),
        ),
    ]
