# Generated by Django 4.2.3 on 2023-08-10 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0019_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='prod_img/no_image.png', upload_to='prod_img'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='prod_img/no_image.png', upload_to='prod_img'),
        ),
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 7, 37, 16, 901908, tzinfo=datetime.timezone.utc)),
        ),
    ]
