# Generated by Django 4.2.3 on 2023-08-10 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0020_product_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 2, 17, 557308, tzinfo=datetime.timezone.utc)),
        ),
    ]
