# Generated by Django 4.2.3 on 2023-08-10 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APİ', '0021_alter_updatecode_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecode',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 2, 30, 990485, tzinfo=datetime.timezone.utc)),
        ),
    ]
